/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "IN1.h"
#include "IN1_aliases.h"
#include "VDDIO_BUFFERED.h"
#include "VDDIO_BUFFERED_aliases.h"
#include "VDDIO_UNBUFFERED.h"
#include "VDDIO_UNBUFFERED_aliases.h"
#include "IN0.h"
#include "IN0_aliases.h"
#include "Opamp.h"
#include "DAC_OUT.h"
#include "DAC_OUT_aliases.h"
#include "IDAC.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "ACTIVE_DATA.h"
#include "Timestamp_ISR.h"
#include "AB_SELECT.h"
#include "RESET_AB_SELECT.h"
#include "DMA_A.h"
#include "DMA_B.h"
#include "COUNTERB.h"
#include "TimestampTimer.h"
#include "timer_clock_2.h"
#include "timer_clock_1.h"
#include "RESET_TIMESTAMP.h"
#include "T1.h"
#include "T1_aliases.h"
#include "T2.h"
#include "T2_aliases.h"
#include "COUNTERA.h"
#include "Clock_2.h"
#include "Clock_1.h"
#include "COUNTER2A.h"
#include "COUNTER1A.h"
#include "SWAP.h"
#include "COUNTER1A_ISR.h"
#include "COUNTER2A_ISR.h"
#include "USBUART_Dp.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dm_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

